services:
  - type: web
    plan: free
    runtime: image
    name: n8n-mojo-automation
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: PORT
        value: "5678"
      - key: N8N_PORT
        value: "5678"

      # Database Configuration
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: dpg-d78abf94tr6s73bvp4gg-a.singapore-postgres.render.com
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: chatbotlogs
      - key: DB_POSTGRESDB_USER
        value: chatbotlogs_user
      - key: DB_POSTGRESDB_PASSWORD
        value: SnoChxBdOP8PowQUESmIJ01Bkb1X8RXk
      - key: DB_POSTGRESDB_SCHEMA
        value: n8n_data
